# Generated by Django 2.1.4 on 2018-12-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='views',
        ),
        migrations.RemoveField(
            model_name='game',
            name='views',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='game',
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='baseapp.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
