# Generated by Django 2.1.4 on 2018-12-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20181228_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
