# Generated by Django 2.1.4 on 2019-01-04 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_auto_20181228_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[['Base', 'Base'], ['Custom', 'Custom']], default='Base', max_length=10),
        ),
    ]
