# Generated by Django 2.1.4 on 2019-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_auto_20190104_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='datetimemodified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
